//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:43:08 PM IST 
//


package com.itzmeds.adfs.client.response.saml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestSecurityTokenResponseCollection"
})
@XmlRootElement(name = "Body", namespace = "http://www.w3.org/2003/05/soap-envelope")
public class Body {

    @XmlElement(name = "RequestSecurityTokenResponseCollection", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512", required = true)
    protected RequestSecurityTokenResponseCollection requestSecurityTokenResponseCollection;

    /**
     * Gets the value of the requestSecurityTokenResponseCollection property.
     * 
     * @return
     *     possible object is
     *     {@link RequestSecurityTokenResponseCollection }
     *     
     */
    public RequestSecurityTokenResponseCollection getRequestSecurityTokenResponseCollection() {
        return requestSecurityTokenResponseCollection;
    }

    /**
     * Sets the value of the requestSecurityTokenResponseCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestSecurityTokenResponseCollection }
     *     
     */
    public void setRequestSecurityTokenResponseCollection(RequestSecurityTokenResponseCollection value) {
        this.requestSecurityTokenResponseCollection = value;
    }

}
