//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:43:08 PM IST 
//

package com.itzmeds.adfs.client.response.saml;

import java.util.Arrays;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "signedInfo", "signatureValue", "keyInfo" })
@XmlRootElement(name = "Signature")
public class Signature {

	@XmlElement(name = "SignedInfo", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
	protected SignedInfo signedInfo;
	@XmlElement(name = "SignatureValue", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
	protected byte[] signatureValue;
	@XmlElement(name = "KeyInfo", required = true)
	protected Signature.KeyInfo keyInfo;

	/**
	 * Gets the value of the signedInfo property.
	 * 
	 * @return possible object is {@link SignedInfo }
	 * 
	 */
	public SignedInfo getSignedInfo() {
		return signedInfo;
	}

	/**
	 * Sets the value of the signedInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link SignedInfo }
	 * 
	 */
	public void setSignedInfo(SignedInfo value) {
		this.signedInfo = value;
	}

	/**
	 * Gets the value of the signatureValue property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getSignatureValue() {
		return signatureValue;
	}

	/**
	 * Sets the value of the signatureValue property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setSignatureValue(byte[] value) {
		this.signatureValue = value;
	}

	/**
	 * Gets the value of the keyInfo property.
	 * 
	 * @return possible object is {@link Signature.KeyInfo }
	 * 
	 */
	public Signature.KeyInfo getKeyInfo() {
		return keyInfo;
	}

	/**
	 * Sets the value of the keyInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link Signature.KeyInfo }
	 * 
	 */
	public void setKeyInfo(Signature.KeyInfo value) {
		this.keyInfo = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "x509Data" })
	public static class KeyInfo {

		@XmlElement(name = "X509Data", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
		protected X509Data x509Data;

		/**
		 * Gets the value of the x509Data property.
		 * 
		 * @return possible object is {@link X509Data }
		 * 
		 */
		public X509Data getX509Data() {
			return x509Data;
		}

		/**
		 * Sets the value of the x509Data property.
		 * 
		 * @param value
		 *            allowed object is {@link X509Data }
		 * 
		 */
		public void setX509Data(X509Data value) {
			this.x509Data = value;
		}

		@Override
		public String toString() {
			return "KeyInfo [x509Data=" + x509Data + "]";
		}

	}

	@Override
	public String toString() {
		return "Signature [signedInfo=" + signedInfo + ", signatureValue=" + Arrays.toString(signatureValue)
				+ ", keyInfo=" + keyInfo + "]";
	}

}
